parameters:
#    meetchatandplay_home_home.example.class: meetchatandplay\Home\HomeBundle\Example

services:
#    meetchatandplay_home_home.example:
#        class: %meetchatandplay_home_home.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
